#!/bin/sh

git diff --cached --diff-filter=ACMR --name-only -z | xargs -0 -n 1 sh -c '
    for FILE; do
        cp $FILE $TEMP/KillBom.tmp
        git checkout -- $FILE

        sed -b -i -e "1s/^\xEF\xBB\xBF//" "$FILE"
        NEEDSADD=`git diff --diff-filter=ACMR --name-only | wc -l`
        if [ $NEEDSADD -ne 0 ]; then
            sed -b -i -e "1s/^\xEF\xBB\xBF//" $TEMP/KillBom.tmp
            echo "Removed UTF-8 BOM from $FILE"
            git add "$FILE"
        fi

        cp $TEMP/KillBom.tmp $FILE
        rm $TEMP/KillBom.tmp
    done
' sh

ANYCHANGES=`git diff --cached --name-only | wc -l`
if [ $ANYCHANGES -eq 0 ]; then
    git commit --no-verify
    exit 1
fi
